export const ADD_PRODUCT = "ADD_PRODUCT";
export const GET_PRODUCTS_FROM_LOCAL_STORAGE = "GET_PRODUCTS_FROM_LOCAL_STORAGE";
export const SUBMIT_ORDER_REQUEST = "SUBMIT_ORDER_REQUEST";
export const SUBMIT_ORDER_SUCCESS = "SUBMIT_ORDER_SUCCESS";
export const SUBMIT_ORDER_ERROR = "SUBMIT_ORDER_ERROR";
